/**
 * codegen d.ts 内容生成（纯字符串拼装，无副作用，最易单测）。
 */

import type { RouteMeta } from '../types.js';

const BODY_METHODS = new Set(['POST', 'PUT', 'PATCH']);

/**
 * 生成 d.ts 内容
 * @param routesByLevel 按层级分组的路由元信息：{ level: { routeName: meta } }
 */
export function generateRouteTypes(routesByLevel: Record<string, Record<string, RouteMeta>>): string {
  const levelEntries = Object.entries(routesByLevel).map(([level, routes]) => {
    const routeEntries = Object.entries(routes).map(([name, meta]) => {
      const defaults = meta.parameter_defaults ?? {};
      const params = (meta.parameters ?? []).map((p) => {
        // URI 中的 {p?} 或有后端默认值的参数 → 生成可选字段，避免调用方被迫传参
        const optional = meta.uri?.includes(`{${p}?}`) || p in defaults;
        return `${p}${optional ? '?' : ''}: string | number;`;
      }).join(' ');
      const method = meta.methods?.find((m) => m.toUpperCase() !== 'HEAD') ?? 'GET';
      const methodUpper = method.toUpperCase();
      const bodyField = BODY_METHODS.has(methodUpper) ? '\n      body: unknown;' : '';
      return `    ${JSON.stringify(name)}: {\n      method: ${JSON.stringify(methodUpper)};\n      params: { ${params} };${bodyField}\n      response: unknown;\n    };`;
    });
    return `  ${JSON.stringify(level)}: {\n${routeEntries.join('\n')}\n  };`;
  });
  return `// AUTO-GENERATED by @route-forge/core codegen. Do not edit.

/**
 * 二级路由类型映射：level → routeName → routeMeta
 * 可通过 module augmentation 增强：
 *   declare module '@route-forge/core' {
 *     interface ForgeRouteMap { admin: { 'users.show': { method: 'GET'; params: { user: string | number }; response: User } } }
 *   }
 */
export interface ForgeRouteMap {
${levelEntries.join('\n')}
}
`;
}
