#!/usr/bin/env node
/**
 * @route-forge/core codegen CLI
 * @see .docs/SPEC.md §4.2
 *
 * 用法：
 *   npx @route-forge/core codegen \
 *     --endpoint http://localhost/_forge/routes \
 *     --levels public,client,manage,admin \
 *     --out src/types/forge-routes.d.ts
 */

import type { RouteMeta } from '../types.js';

export interface CodegenOptions {
  endpoint: string;
  levels: string[];
  out: string;
  responseTypes?: string;
}

const BODY_METHODS = new Set(['POST', 'PUT', 'PATCH']);

/**
 * 解析 argv（最小手写实现，不引入 commander/yargs）
 * 支持：--endpoint VALUE / --endpoint=VALUE / --levels a,b,c / --out PATH / --responseTypes PATH
 */
export function parseArgs(argv: string[]): CodegenOptions {
  const opts: Partial<CodegenOptions> = {};

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = (): string => {
      const v = argv[++i];
      if (v === undefined) {
        throw new Error(`[route-forge/codegen] missing value for ${arg}`);
      }
      return v;
    };

    if (arg === '--endpoint') {
      opts.endpoint = next();
    } else if (arg?.startsWith('--endpoint=')) {
      opts.endpoint = arg.slice('--endpoint='.length);
    } else if (arg === '--levels') {
      opts.levels = next().split(',').map((s) => s.trim()).filter(Boolean);
    } else if (arg?.startsWith('--levels=')) {
      opts.levels = arg.slice('--levels='.length).split(',').map((s) => s.trim()).filter(Boolean);
    } else if (arg === '--out') {
      opts.out = next();
    } else if (arg?.startsWith('--out=')) {
      opts.out = arg.slice('--out='.length);
    } else if (arg === '--responseTypes') {
      opts.responseTypes = next();
    } else if (arg?.startsWith('--responseTypes=')) {
      opts.responseTypes = arg.slice('--responseTypes='.length);
    } else if (arg === '--help' || arg === '-h') {
      printHelp();
      process.exit(0);
    }
  }

  if (!opts.endpoint) {
    console.error('[route-forge/codegen] --endpoint is required');
    printHelp();
    process.exit(1);
  }
  if (!opts.out) {
    console.error('[route-forge/codegen] --out is required');
    printHelp();
    process.exit(1);
  }

  return {
    endpoint: opts.endpoint,
    levels: opts.levels ?? [],
    out: opts.out,
    responseTypes: opts.responseTypes,
  };
}

function printHelp(): void {
  console.log(`
route-forge codegen - generate TS route types from backend summary endpoint

Usage:
  npx @route-forge/core codegen --endpoint URL --out PATH [--levels a,b,c] [--responseTypes PATH]

Options:
  --endpoint URL         Backend summary endpoint (e.g. http://localhost/_forge/routes)
  --levels a,b,c         Optional: explicit level list (skip auto-discovery)
  --out PATH              Output .d.ts file path
  --responseTypes PATH    Optional: JSON file mapping route names to response types
  -h, --help              Show this help
`);
}

/**
 * 拉取摘要端点
 */
export async function fetchSummary(endpoint: string): Promise<{ levels: Record<string, unknown> }> {
  const resp = await fetch(endpoint, { method: 'GET' });
  if (!resp.ok) {
    throw new Error(`summary endpoint ${endpoint} returned ${resp.status}`);
  }
  return (await resp.json()) as { levels: Record<string, unknown> };
}

/**
 * 拉取单个层级的路由元信息
 */
export async function fetchLevel(endpoint: string, level: string): Promise<{ routes: Record<string, RouteMeta> }> {
  const base = endpoint.replace(/\/$/, '');
  const url = `${base}/${encodeURIComponent(level)}`;
  const resp = await fetch(url, { method: 'GET' });
  if (!resp.ok) {
    throw new Error(`level endpoint ${url} returned ${resp.status}`);
  }
  const data = (await resp.json()) as { routes?: Record<string, RouteMeta> };
  return { routes: data.routes ?? {} };
}

/**
 * 生成 d.ts 内容
 * @param routesByLevel 按层级分组的路由元信息：{ level: { routeName: meta } }
 */
export function generateRouteTypes(routesByLevel: Record<string, Record<string, RouteMeta>>): string {
  const levelEntries = Object.entries(routesByLevel).map(([level, routes]) => {
    const routeEntries = Object.entries(routes).map(([name, meta]) => {
      const params = (meta.parameters ?? []).map((p) => `${p}: string | number;`).join(' ');
      const method = meta.methods?.find((m) => m.toUpperCase() !== 'HEAD') ?? 'GET';
      const methodUpper = method.toUpperCase();
      const bodyField = BODY_METHODS.has(methodUpper) ? '\n      body: unknown;' : '';
      return `    ${JSON.stringify(name)}: {\n      method: ${JSON.stringify(methodUpper)};\n      params: { ${params} };${bodyField}\n      response: unknown;\n    };`;
    });
    return `  ${JSON.stringify(level)}: {\n${routeEntries.join('\n')}\n  };`;
  });
  return `// AUTO-GENERATED by @route-forge/core codegen. Do not edit.

/**
 * 二级路由类型映射：level → routeName → routeMeta
 * 可通过 module augmentation 增强：
 *   declare module '@route-forge/core' {
 *     interface ForgeRouteMap { admin: { 'users.show': { method: 'GET'; params: { user: string | number }; response: User } } }
 *   }
 */
export interface ForgeRouteMap {
${levelEntries.join('\n')}
}
`;
}

/**
 * CLI 主入口
 */
export async function main(argv: string[] = process.argv.slice(2)): Promise<void> {
  const opts = parseArgs(argv);

  let levels = opts.levels;
  if (levels.length === 0) {
    try {
      const summary = await fetchSummary(opts.endpoint);
      levels = Object.keys(summary.levels);
    } catch (e) {
      console.error(`[route-forge/codegen] failed to auto-discover levels from summary endpoint: ${(e as Error).message}`);
      console.error('hint: pass --levels explicitly to skip auto-discovery');
      process.exit(1);
    }
  }

  if (levels.length === 0) {
    console.error('[route-forge/codegen] no levels found; pass --levels explicitly');
    process.exit(1);
  }

  const levelFetches = await Promise.allSettled(
    levels.map((lvl) => fetchLevel(opts.endpoint, lvl)),
  );

  const routesByLevel: Record<string, Record<string, RouteMeta>> = {};
  let failedLevels = 0;
  levelFetches.forEach((res, idx) => {
    if (res.status === 'fulfilled') {
      routesByLevel[levels[idx]!] = res.value.routes;
    } else {
      failedLevels++;
      console.warn(`[route-forge/codegen] failed to fetch level "${levels[idx]}": ${(res.reason as Error).message}`);
    }
  });

  const totalRoutes = Object.values(routesByLevel).reduce((sum, r) => sum + Object.keys(r).length, 0);
  if (totalRoutes === 0) {
    console.error('[route-forge/codegen] no routes collected from any level');
    process.exit(1);
  }

  const dts = generateRouteTypes(routesByLevel);

  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const outPath = path.resolve(opts.out);
  const dir = path.dirname(outPath);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(outPath, dts, 'utf8');

  console.log(`[route-forge/codegen] written ${totalRoutes} routes across ${Object.keys(routesByLevel).length} level(s) to ${outPath}`);
  if (failedLevels > 0) {
    console.warn(`[route-forge/codegen] ${failedLevels} level(s) failed; output may be incomplete`);
  }
}

const invokedFromCli = (() => {
  try {
    if (!process.argv[1]) return false;
    const argv1 = process.argv[1].replace(/\\/g, '/');
    return argv1.endsWith('/codegen.js') || argv1.endsWith('/codegen.cjs') || argv1.endsWith('/codegen');
  } catch {
    return false;
  }
})();

if (invokedFromCli) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

export { main as runCodegen };
