#!/usr/bin/env node
/**
 * @route-forge/core codegen CLI
 * @see .docs/SPEC.md §4.2
 *
 * 用法：
 *   npx @route-forge/core codegen \
 *     --endpoint http://localhost/_forge/routes \
 *     --levels public,client,manage,admin \
 *     --out src/types/forge-routes.d.ts
 *
 * 框架阶段：CLI 入口与参数解析占位，实际生成逻辑后续阶段填充。
 */

import type { RouteMeta } from '../types.js';

export interface CodegenOptions {
  endpoint: string;
  levels: string[];
  out: string;
  responseTypes?: string;
}

export function generateRouteTypes(
  routes: Record<string, RouteMeta>,
): string {
  const entries = Object.entries(routes).map(([name, meta]) => {
    const params = (meta.parameters ?? []).map((p) => `${p}: string | number;`).join(' ');
    const method = meta.methods?.find((m) => m.toUpperCase() !== 'HEAD') ?? 'GET';
    return `  ${JSON.stringify(name)}: {
    method: ${JSON.stringify(method.toUpperCase())};
    params: { ${params} };
    response: unknown;
  };`;
  });
  return `// AUTO-GENERATED by @route-forge/core codegen. Do not edit.
declare const routes: {
${entries.join('\n')}
};
`;
}

async function main() {
  // TODO: parse argv (yargs/commander) → fetch each level → merge → write out
  console.log('[route-forge/codegen] placeholder — to be implemented');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

export { main as runCodegen };
